zeesh_plugins=(
    osx
    vi-mode
    python
    django
    virtualenv
    haskell
    mercurial
    git
    vcs-info
    syntax-highlighting
    history-substring-search
    theme
    upstart
    autocomplete
)
source ~/.zsh/zeesh.zsh

export ZEESH_THEME_NORMAL_CHAR='\n⊙'
export ZEESH_THEME_VISUAL_CHAR='\n⊡'
export ZEESH_THEME_INSERT_CHAR='\n›'
export ZEESH_THEME_PROMPT_CHAR=
export PATH=~/.bin:~/.ellipsis/bin:$PATH

alias ack=ag
alias cake=shortcake
alias cask='brew cask'
alias clj='lein repl'
alias hd='noglob hoodoo'
alias http='noglob http'
alias sl=ls
alias utc='date -u'
alias v=vim

export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH

if [ -f ~/.gvm/scripts/gvm ]; then
    source ~/.gvm/scripts/gvm
fi
export GOPATH=$HOME/go:$GOPATH

if [ -f /usr/local/opt/autoenv/activate.sh ]; then
    source /usr/local/opt/autoenv/activate.sh
fi

if [ -e ~/.private/zsh ]; then
    source ~/.private/zsh
fi
